apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-autoscaler
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-autoscaler
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-autoscaler
subjects:
- kind: ServiceAccount
  name: demo-autoscaler
  namespace: particles-test
roleRef:
  kind: ClusterRole
  name: demo-autoscaler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
 name: autoscaler-particles-v1.0.0
spec:
  template:
    metadata:
      name: autoscaler-particles-v1.0.0
    spec:
      containers:
      - name: autoscaler
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: DEPLOYMENT_NAME
          value: particles-v1.0.0
        - name: DEPLOYMENT_LABELS
          value: app=particles,version=1.0.0
        - name: MIN_REPLICAS
          value: "2"
        - name: MAX_REPLICAS
          value: "4"
        image: magneticio/particles-autoscaler:0.1.22
      restartPolicy: OnFailure
      serviceAccountName: demo-autoscaler